kind = "api"
  previewPath = "/"
  title = "API Server"
  version = "1.0.0"
  id = "3B4_FFSkEVBkAeYMFRJ2e"

  [[services]]
  localPort = 8080
  name = "API Server"
  paths = ["/"]

  [services.development]
  run = "pnpm --filter @workspace/api-server run dev"

  [services.development.env]
  WS_PATH = "/api/eagler"

  [services.production]

  [services.production.build]
  args = ["sh", "-c", "PORT=25996 BASE_PATH=/ NODE_ENV=production pnpm --filter @workspace/bungee-ui run build && pnpm --filter @workspace/api-server run build"]

  [services.production.build.env]
  NODE_ENV = "production"

  [services.production.run]
  args = ["node", "--enable-source-maps", "artifacts/api-server/dist/index.mjs"]

  [services.production.run.env]
  PORT = "8080"
  NODE_ENV = "production"
  WS_PATH = "/api/eagler"

  [services.production.health.startup]
  path = "/api/healthz"
  